# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/146lWnYQPsem-IKBJTZoNEH-txkk9Wsap
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install scikit-commpy
from scipy.stats import bernoulli
import commpy
N=int(1e7)
x = bernoulli.rvs(0.1,size=N)  #input signals
y=commpy.channels.bsc(x,0.125)
count=0
for i in range(0,N):
  if y[i]!= x[i]:
     count=count+1
print(count/N)